### ISSUE TITLE
Runtime API implementation status

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/godot-explorer#33]
Glossary: 
- **Foundation client**: refers to https://github.com/decentraland/unity-renderer/
- 🏷️ : inheritance from SDK6
- 
## ✅ `~system/CommsApi`
- [ ] #144

##  ✅ `~system/PortableExperiences`
- [x] `async spawn`
- [x] `async kill`
- [ ] `async exit`
- [x] `async getPortableExperiencesLoaded`

## ✅ `~system/RestrictedActions`
- [x] `async movePlayerTo`
- [x] `async teleportTo`
- [x] `async triggerEmote`
- [x] `async changeRealm`
- [x] `async openExternalUrl`
- [x] `async openNftDialog`
- `async setCommunicationsAdapter` :clock1:  not planned, Foundation doesn't implemented it
- [x] #143

## ✅ `~system/Runtime`
- [x] `async getRealm`
- [x] `async getWorldTime`
- [x] `async readFile`
- [x] `async getSceneInformation`

## ✅ `~system/SignedFetch`
- [x] `async signedFetch`
- [x] `async getHeaders`

## ✅ `system/EngineApi` (SDK7 methods)
- [x] `async crdtSendToRenderer` ✅ 
- [x] `async crdtGetState` ✅ 
- [x] `async crdtGetMessageFromRenderer` :x: exposed
   - [x] remove

## ⚠️🏷️ `system/EngineApi` (SDK6 methods)
The implementation of this would be to have compatibility with scene where it was exposed and also SDK6 bridge.
- [x] `async sendBatch` @deprecated :warning:  🏷️
- [x] `async subscribe` @deprecated :warning: 🏷️
- [x] `async unsubscribe` @deprecated :warning: 🏷️
   
## ⚠️🏷️  `~system/Players`
- [x] `async getPlayerData`
- [x] `async getPlayersInScene`
- [x] `async getConnectedPlayers`

## ⚠️🏷️ `~system/UserIdentity` 
- [x] `async getUserPublicKey`
- [x] `async getUserData`

## :warning: `~system/EthereumController`
Marked as deprecated for SDK7 runtime:
- [x] `async requirePayment` :x: 🏷️
- [x] `async signMessage` :x: 🏷️
- [x] `async convertMessageToObject` :x: 🏷️
- [x] `async getUserAccount` :x: 🏷️

The only exposed to SDK7 should be:
- [x]  `async sendAsync` ✅ 

## :x: 🏷️ `~system/UserActionModule`
- [x] `async requestTeleport`
  - [ ] :x: remove

## :warning: 🏷️ `~system/CommunicationsController`
- [x] `async send`: marked as deprecated in https://github.com/decentraland/protocol/blob/75f18e8094a0435594eecfbb6e020614b2a86c69/proto/decentraland/kernel/apis/communications_controller.proto#L11 #264 

## :eyes:  :x: `~system/Scene`
- [x] `async getSceneInfo` :warning: 

##   :x:🏷️ `~system/EnvironmentApi` (deprecated)
This API shouldn't be exposed to SDK7
- `async getBootstrapData`
- `async isPreviewMode`
- `async getPlatform`
- `async areUnsafeRequestAllowed`
- `async getCurrentRealm`
- `async getExplorerConfiguration`
- `async getDecentralandTime`

## `~system/Testing`
- [x] `async logTestResult`
- [x] `async plan`
- [x] `async setCameraTransform`

# Current apis.d.ts exposed
```ts
/**
  * CommsApi
  */
declare module "~system/CommsApi" {
    export function getActiveVideoStreams(body: VideoTracksActiveStreamsRequest): Promise<VideoTracksActiveStreamsResponse>;
}

/**
  * CommunicationsController
  */
declare module "~system/CommunicationsController" {
    export function send(body: RealSendRequest): Promise<RealSendResponse>;
}

/**
  * EngineApi
  */
declare module "~system/EngineApi" {
    export function sendBatch(body: ManyEntityAction): Promise<SendBatchResponse>;
    export function subscribe(body: SubscribeRequest): Promise<SubscribeResponse>;
    export function unsubscribe(body: UnsubscribeRequest): Promise<UnsubscribeResponse>;
    export function crdtSendToRenderer(body: CrdtSendToRendererRequest): Promise<CrdtSendToResponse>;
    export function crdtGetState(body: CrdtSendToRendererRequest): Promise<CrdtGetStateResponse>;
    export function crdtGetMessageFromRenderer(body: CrdtMessageFromRendererRequest): Promise<CrdtMessageFromRendererResponse>;
}

/**
  * EnvironmentApi
  */
declare module "~system/EnvironmentApi" {
	export function getBootstrapData(body: GetBootstrapDataRequest): Promise<BootstrapDataResponse>;
    export function isPreviewMode(body: IsPreviewModeRequest): Promise<PreviewModeResponse>;
    export function getPlatform(body: GetPlatformRequest): Promise<GetPlatformResponse>;
    export function areUnsafeRequestAllowed(body: AreUnsafeRequestAllowedRequest): Promise<AreUnsafeRequestAllowedResponse>;
    export function getCurrentRealm(body: GetCurrentRealmRequest): Promise<GetCurrentRealmResponse>;
    export function getExplorerConfiguration(body: GetExplorerConfigurationRequest): Promise<GetExplorerConfigurationResponse>;
    export function getDecentralandTime(body: GetDecentralandTimeRequest): Promise<GetDecentralandTimeResponse>;
}

/**
  * EthereumController
  */
declare module "~system/EthereumController" {
    export function requirePayment(body: RequirePaymentRequest): Promise<RequirePaymentResponse>;
    export function signMessage(body: SignMessageRequest): Promise<SignMessageResponse>;
    export function convertMessageToObject(body: ConvertMessageToObjectRequest): Promise<ConvertMessageToObjectResponse>;
    export function sendAsync(body: SendAsyncRequest): Promise<SendAsyncResponse>;
    export function getUserAccount(body: GetUserAccountRequest): Promise<GetUserAccountResponse>;
}

/**
  * Players
  */
declare module "~system/Players" {
    export function getPlayerData(body: GetPlayerDataRequest): Promise<PlayersGetUserDataResponse>;
    export function getPlayersInScene(body: GetPlayersInSceneRequest): Promise<PlayerListResponse>;
    export function getConnectedPlayers(body: GetConnectedPlayersRequest): Promise<PlayerListResponse>;
}

/**
  * PortableExperiences
  */
declare module "~system/PortableExperiences" {
    export function spawn(body: SpawnRequest): Promise<SpawnResponse>;
    export function kill(body: KillRequest): Promise<KillResponse>;
    export function exit(body: ExitRequest): Promise<ExitResponse>;
    export function getPortableExperiencesLoaded(body: GetPortableExperiencesLoadedRequest): Promise<GetPortableExperiencesLoadedResponse>;
}

/**
  * RestrictedActions
  */
declare module "~system/RestrictedActions" {
    export function movePlayerTo(body: MovePlayerToRequest): Promise<MovePlayerToResponse>;
    export function teleportTo(body: TeleportToRequest): Promise<TeleportToResponse>;
    export function triggerEmote(body: TriggerEmoteRequest): Promise<TriggerEmoteResponse>;
    export function changeRealm(body: ChangeRealmRequest): Promise<SuccessResponse>;
    export function openExternalUrl(body: OpenExternalUrlRequest): Promise<SuccessResponse>;
    export function openNftDialog(body: OpenNftDialogRequest): Promise<SuccessResponse>;
    export function setCommunicationsAdapter(body: CommsAdapterRequest): Promise<SuccessResponse>;
    export function triggerSceneEmote(body: TriggerSceneEmoteRequest): Promise<SuccessResponse>;
}

/**
  * Runtime
  */
declare module "~system/Runtime" {
    export function getRealm(body: GetRealmRequest): Promise<GetRealmResponse>;
    export function getWorldTime(body: GetWorldTimeRequest): Promise<GetWorldTimeResponse>;
    export function readFile(body: ReadFileRequest): Promise<ReadFileResponse>;
    export function getSceneInformation(body: CurrentSceneEntityRequest): Promise<CurrentSceneEntityResponse>;
}

/**
  * Scene
  */
declare module "~system/Scene" {
    export function getSceneInfo(body: GetSceneRequest): Promise<GetSceneResponse>;
}

/**
  * SignedFetch
  */
declare module "~system/SignedFetch" {
    export function signedFetch(body: SignedFetchRequest): Promise<FlatFetchResponse>;
    export function getHeaders(body: SignedFetchRequest): Promise<GetHeadersResponse>;

}

/**
  * Testing
  */
declare module "~system/Testing" {
    export function logTestResult(body: TestResult): Promise<TestResultResponse>;
    export function plan(body: TestPlan): Promise<TestPlanResponse>;
    export function setCameraTransform(body: SetCameraTransformTestCommand): Promise<SetCameraTransformTestCommandResponse>;
}

/**
  * UserActionModule
  */
declare module "~system/UserActionModule" {
    export function requestTeleport(body: RequestTeleportRequest): Promise<RequestTeleportResponse>;
}

/**
  * UserIdentity
  */
declare module "~system/UserIdentity" {
    export function getUserPublicKey(body: GetUserPublicKeyRequest): Promise<GetUserPublicKeyResponse>;
    export function getUserData(body: GetUserDataRequest): Promise<GetUserDataResponse>;
}
```
