### ISSUE TITLE
VR Roadmap (Godot)

### ISSUE THREAD

**Issue by kuruk-mm** [decentraland/godot-explorer#445]
- [ ] Change the world ray cast to the right hand instead of the Main Camera
- [ ] Add watch to show/hide the 2D UI
- [ ] When the scene is loading, you can see the emissive materials, and it should be dark
- [ ] Fix Player Physics to match the Mobile version
- [ ] Add layouts to know which meta quest input does what in the world
- [x] Emotes are not being played
- [ ] Add a virtual keyboard for when you need to text (there is one in the godot-xr-tools)
- [ ] Other players see VR players "flying" (the broadcasted position is a bit "high", there are some centimetres from the floor)
- [x] When you go to Genesis Plaza, it teleports you to -9,-9, but sometimes you're at -10,-10 and it doesn't load Genesis Plaza (looks like it's the offset of the VR room position)
- [ ] Discuss removing the teleport and allowing walking, or having a "cooldown" to walk at the same speed as other clients

**Comment by abhisharma9876** [comment]
try this
https://bit.ly/4gwC82r
I put the necessary dlls in the archive
